stages:
  - cypress
  - playwright

cypress:
  image: node:latest
  stage: test

  before_script:
    - apt-get update
    - apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - Xvfb :99 -ac &
    - export DISPLAY=:99

  script:
    - npm ci
    - npx cypress run --record --key $CYPRESS_CLOUD_KEY

  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week

playwright:
  stage: test
  image: mcr.microsoft.com/playwright:v1.49.1-noble
  parallel: 2
  script:
    - npm ci
    - npm run playwright:test