name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          Xvfb :99 -ac &
          export DISPLAY=:99

      - run: npm ci --legacy-peer-deps

      - name: Install Cypress Dependencies
        uses: cypress-io/github-action@v4

      - name: Copy environment variables
        run: cp .env.example .env

      - name: Run Cypress Tests
        run: xvfb-run -a npm run cypress:test

  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          Xvfb :99 -ac &
          export DISPLAY=:99

      - run: npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Copy environment variables
        run: cp .env.example .env

      - name: Run Playwright Tests
        run: xvfb-run -a npm run playwright:test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30